import { Recipe } from './types';

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Grilled Chicken with Vegetables',
    description: 'A healthy and delicious grilled chicken dish with seasonal vegetables',
    ingredients: [
      { name: 'Chicken breast', amount: '2', unit: 'pieces' },
      { name: 'Bell peppers', amount: '2', unit: 'pieces' },
      { name: 'Zucchini', amount: '1', unit: 'piece' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
      { name: 'Black pepper', amount: '1/2', unit: 'tsp' },
    ],
    instructions: [
      'Preheat grill to medium-high heat',
      'Season chicken breast with salt and pepper',
      'Brush vegetables with olive oil',
      'Grill chicken for 6-7 minutes per side',
      'Grill vegetables for 4-5 minutes',
      'Let chicken rest for 5 minutes before serving',
    ],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: 'Easy',
    category: 'Main Course',
    tags: ['healthy', 'grilled', 'chicken'],
    dateEaten: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Vegetarian Pasta Primavera',
    description: 'Fresh pasta with spring vegetables in a light cream sauce',
    ingredients: [
      { name: 'Pasta', amount: '400', unit: 'g' },
      { name: 'Cherry tomatoes', amount: '200', unit: 'g' },
      { name: 'Broccoli', amount: '1', unit: 'cup' },
      { name: 'Carrots', amount: '2', unit: 'pieces' },
      { name: 'Heavy cream', amount: '1/2', unit: 'cup' },
      { name: 'Parmesan cheese', amount: '50', unit: 'g' },
    ],
    instructions: [
      'Cook pasta according to package instructions',
      'Sauté vegetables in a large pan',
      'Add cream and bring to a simmer',
      'Toss cooked pasta with sauce',
      'Serve with grated parmesan',
    ],
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Medium',
    category: 'Main Course',
    tags: ['vegetarian', 'pasta', 'italian'],
    dateEaten: new Date('2024-01-12'),
  },
  {
    id: '3',
    name: 'Salmon Teriyaki Bowl',
    description: 'Pan-seared salmon with teriyaki glaze served over rice',
    ingredients: [
      { name: 'Salmon fillet', amount: '4', unit: 'oz' },
      { name: 'Rice', amount: '1', unit: 'cup' },
      { name: 'Teriyaki sauce', amount: '1/4', unit: 'cup' },
      { name: 'Edamame', amount: '1/2', unit: 'cup' },
      { name: 'Carrots', amount: '1', unit: 'piece' },
      { name: 'Sesame seeds', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Cook rice according to package instructions',
      'Heat pan over medium-high heat',
      'Sear salmon skin-side down for 4 minutes',
      'Flip and cook for 3 more minutes',
      'Brush with teriyaki sauce in the last minute',
      'Serve over rice with vegetables',
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 1,
    difficulty: 'Medium',
    category: 'Main Course',
    tags: ['salmon', 'asian', 'healthy'],
    dateEaten: new Date('2024-01-10'),
  },
];

